modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "hologram_api"
version = "${version}"
displayName = "Hologram API"
authors = "ray"
description = '''
API for client-side in world text rendering.
'''
logoFile = "assets/hologram_api/icon.png"

[[dependencies.hologram_api]]
modId = "forge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hologram_api]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
